### ISSUE TITLE
Yarn errors out when trying to setup the project

### ISSUE THREAD

**Issue by ravieze** [voxeet/voxeet-uxkit-web-mixerlayout#4]
When trying to setup the project, I ran the yarn command to fetch all the necessary dependencies. I get the below error. Is this expected?

![image](https://user-images.githubusercontent.com/5900517/94182189-3aaed880-febe-11ea-9168-7d587c8dffa7.png)

**Comment by ravieze** [comment]
Yes the compilation issue is fixed. But i think there are quite a few more. 

1. conferenceRoom.js is expecting Access TOken and refresh token. From dolby.io Dashboard webpage I only see clientid, secret and not AccessTOken and refreshToken. HOw to fix this?
![image](https://user-images.githubusercontent.com/5900517/94257928-b2761500-ff49-11ea-9168-390a74b7d10f.png)

2. When i try to open the webpage at https://localhost:8081 i see a white page. 
![image](https://user-images.githubusercontent.com/5900517/94257873-970b0a00-ff49-11ea-8800-274de8e97c91.png)

I see that Voxeet is acquired by Dolby and hence I am following this tutorial. The aim here is to get the below layout done (faces are pixilated for privacy. The Image is more to drive the idea that I want to be able to create multiple layouts or create overlays using voxeets a.k.a. dolby.io)

![image](https://user-images.githubusercontent.com/5900517/94258364-5d86ce80-ff4a-11ea-9e1b-f212dde6bb33.png)

**Comment by ravieze** [comment]
The doc says

> To make the layout works with our mixer, you will need to host and deploy. When your layout is ready to deploy, go to your account on https://developer.voxeet.com and add your Mixer layout url inside the input associated.


But when i logint to dashboard i dont see any such place to enter a URL

**Comment by ravieze** [comment]
Hi,

I deleted yarn.lock and the issue is now fixed. HOwever some confusion is still there. THe docs says

> <input type="hidden" value="accessToken" id="accessToken" name="accessToken"/>
> <input type="hidden" value="refreshToken" id="refreshToken" name="refreshToken"/>

HOwver from dolby dashboard its not clear where to find it. For now i entered access key and secret from the dashboard of dolby. Now the server comes up only to render only white page 

![white-page](https://user-images.githubusercontent.com/5900517/94268540-f291c380-ff5a-11ea-89a5-0dff05696090.png)

Any thoughts?-

**Comment by FabienLavocat** [comment]
Hi @ravieze the README has just been updated, it should be more clear now on how to use this application.
At the bottom of the file `src/app/components/ConferenceRoom.js`, use the following code:

```
ConferenceRoom.defaultProps = {
  isDemo: true,
  consumerKey: "<INSERT_YOUR_KEY>",
  consumerSecret: "<INSERT_YOUR_SECRET>"
};
```

Then, run the command `yarn run build` and then `yarn start`. If you are having an SSL issue with your web browser, I suggest to open the file `webpack.config.js` and replace `https: true` into `https: false`. Then, run the command `yarn start` and navigate to the web page http://localhost:8081/index.html

**Comment by veloware** [comment]
Unfortunately I didn't find the updated readme any more clear to be honest, the comment above is more helpful. I was facing the same issue regarding the lock file, also had to change the host from 0.0.0.0 to 127.0.0.1 and https to http in the webpack config to get to the landing screen.  Once I provide a conference name (I'm just supplying a random name here - e.g. 'test'), select a layout type and click Join Conference, I just get white screen.  I'm obviously missing something here, but its not clear at all on how to use this?

**Comment by ravieze** [comment]
I figured out things, a little. Seems like this project is more to show how it looks like: when multiple users join the conference using webrtc. You can change layout using CSS or ever, but you cant brodcast the layout to RTMP url. I think the name of the project is misleading. You cant change layouts and broadcast the changed layout to an RTMP url by using this project -- what i mean is we cant do the below. 

![image](https://user-images.githubusercontent.com/5900517/95447784-e73d8f80-097f-11eb-9747-c0bb6f94dfba.png)

**Comment by ravieze** [comment]
I think its better to use: voxeet-sdk-browser-gettingstarted and host the same using ngrok.com to get https:// enabled and when multiple users join the layout self adjusts to something and only this layout can be broadcasted to RTMP/ youtube. 

What I was not able to do was to customize the layout. I am not sure why readme is not done good.

**Comment by FabienLavocat** [comment]
@veloware Once you create provide a conference alias, join the same conference using another application, you can use the project [voxeet/voxeet-sdk-browser-gettingstarted](https://github.com/voxeet/voxeet-sdk-browser-gettingstarted) to join the same conference and you will see the stream showing up on the mixer layout.

**Comment by FabienLavocat** [comment]
@ravieze Thank you, that is great feedback, I will make sure to update our documentation to make it more clear what this project is about.
The idea of this Web Mixer Layout project is to generate a UI that represents your conference (or webinar...). Participants will use the iOS, Android or Web applications that you are going to create (have look at the getting-started repos) to join a conference, share audio and video streams, share content (video, presentation). If you wish to record the conference into an .mp4 file, or broadcast the conference to RTMP (youtube...), then we use the Mixer Layout application that you build (this project), we record it into a video/audio stream and send it to the RTMP endpoint.

The "demo mode" in this project is here to help you design the UI the way to want for a recording or a broadcast.

I hope this makes more sense.

**Comment by veloware** [comment]
Is this to generate the likes of a ConferenceRoom component to be used in an application _instead_ of the UIKit's Conference Room?  Im still not quite sure the purpose of this repo? Is it for the host/speaker of the webinar or for the watchers of the webinar?

**Comment by FabienLavocat** [comment]
For example, using the web sdk, you can customize the presentation for your web users, using the Android SDK you can customize how you want to layout the video streams on the mobile screen. Also, you can have a presentation for active participants and a different layout for listeners.

Now, when you want to record a conference, or broadcast it to external listeners, we want you to be able to customize the layout as well. Both of those scenarios are handler on our own server. To customize that recording layout, you need to create an application (this repo is a sample of what you can do), provide it to our server and when you request a conference to be recorded, then we will load the application and record the layout you've built.

I hope it makes it more clear.
